### ISSUE TITLE
Crash if an output is "empty"

### ISSUE THREAD

**Issue by deliciouslytyped** [volkerp/zfstui#1]
This tool is pretty cute, thanks for making it!

There's a crash in dialogs.py if you don't have any volumes (for example), I just replaced `lines[0]` with `lines[0] if lines else ""`, but I didn't look hard enough to check whats really going on. In this case the output of `zfs list` doesn't match the tabular format, it just says `no datasets available`

**Comment by deliciouslytyped** [comment]
Pressing [ret] in a tab with no entries will cause a crash.

**Comment by volkerp** [comment]
> This tool is pretty cute, thanks for making it!

Thanks! I guess you're the only one who actually uses it ;-)

> There's a crash in dialogs.py if you don't have any volumes (for example), I just replaced `lines[0]` with `lines[0] if lines else ""`, but I didn't look hard enough to check whats really going on. In this case the output of `zfs list` doesn't match the tabular format, it just says `no datasets available`

I'll look into it. The tool is in it's infancy and has probably a lot more bugs and lacking features.
